name = "DynaMeth"
uuid = "ed7125c6-181f-4a88-94ec-310792e5ee2e"
authors = ["Jo1931 <johanneslpld@googlemail.com.de>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
CSV = "0.10.15"
ComponentArrays = "0.15.31"
DataFrames = "1.8.1"
Dierckx = "0.5.4"
DifferentialEquations = "7.17.0"
FileIO = "1.17.1"
ForwardDiff = "1.3.1"
Ipopt = "1.14.0"
JLD2 = "0.6.3"
JuMP = "1.29.3"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
MAT = "0.11.4"
NonlinearSolve = "4.14.0"
Optim = "2.0.0"
PGFPlotsX = "1.6.2"
Plots = "1.41.4"
Statistics = "1.11.1"
Sundials = "5.1.0"
UnPack = "1.0.2"
